// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Change this line to match Vercel exactly
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANONYMOUS_KEY; 

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  // ... rest of your code